### PR TITLE
Fix typo and broken link in documentation

### PR DESCRIPTION
**Pull request by Balatzar**
A fix for a typo and a broken link.

There is another issue on the live documentation website for the link targeting the Application Options page in the sidebar. The link sends to https://bullettrain.co/docs/docs/application-options.md which is invalid. I could not figure out how to fix the issue, the code in this repo seems right.

image

### CODE REVIEW

**Comment by gazayas** [comment]
Hey @Balatzar, I cleaned up some of the docs recently but totally didn't catch the misspelling of "Internationalization", Thanks!

**Comment by Balatzar** [comment]
Hello @gazayas! No problem :) Where you able to locate the issue with the application-options.md link?

**Comment by gazayas** [comment]
@Balatzar We fixed it in #94, I think it just needs to be updated to the actual docs website.

**Comment by Balatzar** [comment]
Ahh that's why i wasnt able to see the issue. Perfect, i'll close this one!

**Pull request closed without merging**
