### PR TITLE
Revert "Revert #334 - Themes localization"

### PR DESCRIPTION
**Pull request by jagthedrummer**
Unfortunately we had to revert bullet-train-co/bullet_train-core#334 because it had broken the date and date/time pickers. After merging #334 a lot of stuff changed so I couldn't generate a clean revert PR. So #389 was a "fresh" PR that was a commit-by-commit revert of each of the commits in #334.

This PR is an auto-generated revert of #389. Which effectively means it's a revert of the revert of #334. AKA it reintroduces the changes from #334 and brings back the theme localization that was done in that PR.

I'm just opening this so that we don't lose track of it, and so there's a place to pick back up if/when someone has the time.

Reverts bullet-train-co/bullet_train-core#389

### CODE REVIEW

**Comment by jagthedrummer** [comment]
Strangely, all tests are passing in _this_ repo, but not in the starter repo when linked to this same branch. I suspect that we're not linking _everything_ in the `core` repo to the starter repo when we check it out in CI.

**Comment by jagthedrummer** [comment]
It turns out that the test discrepancy was because we just weren't running as many tests here as were are in the stater repo. I added the missing tests to the circle config, and now this PR is showing the test failures.

**Comment by gazayas** [comment]
I found that the changes I added here https://github.com/bullet-train-co/bullet_train/pull/828/commits/96fb534681e95e0fffeca7713e13a05c15a09012 and here https://github.com/bullet-train-co/bullet_train/pull/828/commits/b411a2173974bd1084155777d753d34260756913 fixed these tests.

I took these from https://github.com/bullet-train-co/bullet_train/pull/811/ which is also related.

image

**Comment by 3pns** [comment]
I started investigating the new test failure by recovering my PR  here https://github.com/bullet-train-co/bullet_train-core/pull/393

I verified manually that the scaffolding system still works both with the latest version of the starter repo and on our side as well.

I see that the tests passes on master, I can only think of 2 possible scenarios :
- we may not link everything in the core repo to the starter repo as you suggested @jagthedrummer . I have seen the pickers not load when I have done this when doing my tests. 
- my changes may prevent the daterangepicker to load during system tests ? This is the reason I used the trick that @gazayas  pointed out in https://github.com/bullet-train-co/bullet_train/pull/811 .

**Comment by jagthedrummer** [comment]
Hey @3pns, thanks for picking this back up! You can see the tests in question failing on #393. Here's a link directly to CI: https://app.circleci.com/pipelines/github/3pns/bullet_train-core/6/workflows/a37eff84-3695-48c9-92bf-605ef201b98f/jobs/20

Note that these are in `test/system/super_scaffolding_partial_test.rb` which is not run as part of the regular system tests.

There are instruction included in the top of that test file for how to run them locally. Previously when I had linked _every gem_ that's in `core` (including ones that aren't explicitly listed in `Gemfile` but that are included in `Gemfile.lock`) to my local starter repo that test would fail for me in the same way that it fails in CI.

**Comment by jagthedrummer** [comment]
Closing this in favor of #393.

**Comment by gazayas** [comment]
@3pns
> we may not link everything properly in the core repo to the starter repo as you suggested @jagthedrummer . I have seen the pickers not load when I have done this when doing my tests locally.

☝️

Excited for #396! It's been a long time coming.

**Comment by jagthedrummer** [comment]
Reopening this temporarily to see what effect #396 has on testing this branch.

**Pull request closed without merging**
