### PR TITLE
Fix various dark mode styles

### PR DESCRIPTION
**Pull request by gazayas**
Closes https://github.com/bullet-train-co/bullet_train/issues/600

I also noticed the fly out menus only had the primary blue style for light mode, so I added `darkPrimary` for those too.

### Changes
1. Hover background of Team index records.
2. Hover background of Pagy navigation buttons.
3. Background of new fly out menus.

# Before

https://user-images.githubusercontent.com/10546292/211246574-1c31cb8d-1157-49f0-96a2-7be871c0cb17.mov

https://user-images.githubusercontent.com/10546292/211246680-e253f4f0-322f-4a19-b40f-74326345e3cf.mov

# After

https://user-images.githubusercontent.com/10546292/211246788-eb001d66-741a-4317-b619-eed1783ad1a1.mov

https://user-images.githubusercontent.com/10546292/211246801-02c143e9-f95c-4e91-9fe3-99789dd422a0.mov

# Styling decisions
I decided to style things this way because I saw that the active buttons (like the `Dashboard` button in the menu in this screenshot) use `dark:bg-black dark:bg-opacity-10`.

Active Button Style

### CODE REVIEW

**Comment by gazayas** [comment]
I think we'll need to change https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-api/app/views/account/platform/connections/new.html.erb too because `sealBlue` doesn't exist anymore in our current context, I don't see it anywhere else in the repo though.

**Comment by gazayas** [comment]
Since `app/views/account/platform/connections/new.html.erb` was added in #34, I set things up with Zapier and fired a webhook, but I'm still not quite sure how to access the connections view, so I'll leave this on be for now.

**Comment by gazayas** [comment]
Ok, I didn't realize the new connections page is the pop-up when you're connecting to your team via Zapier, finally figured it out.

## Before

Zapier Before

## After

Zapier After

**Comment by andrewculver** [comment]
Fixed a lot of these as part of https://github.com/bullet-train-co/bullet_train-core/pull/106 . Do you want to do a spot check and make sure I got all of them? Otherwise, we should start a new branch to fix anything that's still broken, since so much changed.

**Comment by gazayas** [comment]
@andrewculver Sure thing, I'll take a look over the views in light/dark mode to see if I find anything fishy

**Pull request closed without merging**
