### PR TITLE
[WIP] Showcase Example for Field Partials

### PR DESCRIPTION
**Pull request by ps-ruby**
This is still work in the process. I am just done adding the all available partials fields.

### CODE REVIEW

**Comment by kaspth** [comment]
@ps-ruby nice, let me know when this is ready for review then I'll look through them.

**Comment by ps-ruby** [comment]
> @ps-ruby nice, let me know when this is ready for a review then I'll look through them.

Sure

@andrewculver has asked me to add a showcase for theme partials and I have overlooked the requirement and added for field partial. Anyway, I will complete it and let you know.

**Comment by jagthedrummer** [comment]
Hey @ps-ruby, just curious if you're planning to finish this out, or if we should close it.

**Comment by kaspth** [comment]
Actually, let me take this over unless you want to @ps-ruby 😄

**Comment by ps-ruby** [comment]
> Actually, let me take this over unless you want to @ps-ruby 😄

@kaspth You can take over, sorry for keeping it on hold for so long.

**Comment by kaspth** [comment]
Looks like we're missing some JavaScript to get some of these fields to work. It also looks like the starter repo only imports the `trixEditor` from fields https://github.com/bullet-train-co/bullet_train/blob/2836a0e4e62b0c0612b88573b7ad9218a852ce2f/app/javascript/application.js#L27

…so I'm not sure how these fields work in Bullet Train apps.

**Comment by jagthedrummer** [comment]
@kaspth when I grep for `fields` I'm seeing a couple of more imports in the starter repo.

```
app/javascript/application.js:import { trixEditor } from "@bullet-train/fields"
app/javascript/controllers/index.js:import { controllerDefinitions as bulletTrainFieldControllers } from "@bullet-train/fields"
app/javascript/intl-tel-input-utils.js:import "@bullet-train/fields/app/assets/javascripts/intl-tel-input-utils.js"
```

**Comment by kaspth** [comment]
I'd accidentally broken including the application assets in Showcase in #378, so I'm fixing that here https://github.com/bullet-train-co/bullet_train-core/pull/403 — after that, the JavaScript works again.

**Comment by kaspth** [comment]
Noticed this, which will be a fix later:

> [Warning] Please replace data-target="fields--emoji-picker.display" with data-fields--emoji-picker-target="display". The data-target attribute is deprecated and will be removed in a future version of Stimulus. –
> &lt;span data-target="fields--emoji-picker.display"&gt;😘&lt;/span&gt;

**Comment by kaspth** [comment]
Ok, I think this puts us in a much better spot than we were before, thanks for @ps-ruby for the groundwork on this!

**Pull request merged**
