### PR TITLE
Introduce syntax highlighting

### PR DESCRIPTION
**Pull request by jagthedrummer**
I'm taking over https://github.com/bullet-train-co/bullet_train-core/pull/355 from @vfonic and since I can't push to his branch I'm starting a new branch with his work, plus a few modifications.

### CODE REVIEW

**Comment by kaspth** [comment]
Come to think of it, it might be nice to move the `commonmarker` upgrade to just `bullet_train`'s Gemfile (instead of the `gemspec`), like in https://github.com/bullet-train-co/bullet_train-core/pull/355/files#diff-2e2559a7b01655e89a09351f8c04d2560b25cfc28b7918ff5473b26bea424f39R18

That way we don't force the `pre` upgrade onto users, but Bullet Train's public docs can still be updated.

We may need to add a `if Commonmarker::VERSION >= "1.x"` in the `markdown` helper though and scope the implementations.

**Comment by jagthedrummer** [comment]
@kaspth I wondered about needing a different version but as far as I can tell the current version of that helper is using the `1.x` syntax. I'm a little surprised that it was working with versions < 1.

If you think there's a better way to handle the version bump I'm down for reviewing and merging a PR for it.

**Comment by vfonic** [comment]
The helper was updated as you can see in this PR, if that's what you're referring to. So, before this PR, the code used commonmarker v <1 syntax and v0.x gem. After this PR the code uses v1. X syntax and v1.x (pre) gem version.

**Comment by jagthedrummer** [comment]
Oh dang, you're right! I somehow missed that, or was looking in the wrong place. Yeah, we may need that conditional that you mentioned @kaspth. Or we leave the dependency update in the `.gemspec` and force it.

**Comment by kaspth** [comment]
I'll make a PR tomorrow to move the version lock to the Gemfile, so we don't force the `pre`-releases on users. They may be using the `markdown` helper in production to render non-documentation content, and if we've got the version lock in the gemspec and anything goes wrong they can't downgrade. — I mean they can downgrade `bullet_train-core` but that may have others issues with it too.

**Pull request merged**
