### PR TITLE
Use `Gem.find_files` in `bt:link` to avoid loading the environment

### PR DESCRIPTION
**Pull request by kaspth**
A potential simplification for our `bt:link` task.

### CODE REVIEW

**Comment by andrewculver** [comment]
@kaspth Excited for this!

**Comment by kaspth** [comment]
I can't get any of the failing tests to fail locally and they're all of the `Capybara::Ambiguous: Ambiguous match, found 2 elements matching` variety where's 2 potential matches. I have no idea what's going on. @gazayas @andrewculver have any of you run into this before?

**Comment by gazayas** [comment]
I haven't run into this error before so I'm not sure :thinking:

The tests fail for me locally though with the same error, and it looks like the styles aren't being loaded in the browser:

## Duplicate links
image

## Sign in page
image

**Comment by kaspth** [comment]
@gazayas thank you, I think I got it fixed now — it seems there were some leftover `.bt-link` files in gems that shouldn't have them.

There's a reactivity test that's failing, but it's failing on #154 too, so I think that's unrelated.

**Comment by kaspth** [comment]
Ah just needed a merge from main.

**Comment by gazayas** [comment]
@kaspth No problem! I wish I could've been more help than just posting screenshots 😅️ Excited for this PR!

**Comment by kaspth** [comment]
@gazayas no worries, the screenshots were actually really helpful!

**Pull request merged**
