### PR TITLE
Super scaffolding fix for `--sortable` with a multi word parent

### PR DESCRIPTION
**Pull request by jagthedrummer**
Fixes https://github.com/bullet-train-co/bullet_train/issues/1421

### CODE REVIEW

**Comment by gazayas** [comment]
@jagthedrummer Nice, I confirmed that this properly finds the underscored parent in the migration and adds the sort order column after it.

I'm having trouble actually sorting the records though. Doesn't seem to be working on `main` either when just super scaffolding a simple model. This PR definitely accounts for the missing column though!

**Comment by jagthedrummer** [comment]
> I'm having trouble actually sorting the records though.

Sounds like we might have another issue. I'll look into it.

**Comment by jagthedrummer** [comment]
@gazayas I looked into the sorting thing and it does work for me, but it's not at all obvious that the list is sortable and that you can drag the list items around. We should probably make it more obvious. I'll open a ticket about that.

**Comment by gazayas** [comment]
@jagthedrummer Looks like I just needed to run `yarn install`, it's working for me now :+1:

**Pull request merged**
