### PR TITLE
Scaffold routes properly for deeply nested Action Model actions

### PR DESCRIPTION
**Pull request by gazayas**
Depends on https://github.com/bullet-train-pro/bullet_train-action_models/pull/94

- [x] Ensure the routes for the example in https://github.com/bullet-train-pro/bullet_train-action_models/issues/93 are scaffolded properly.

### CODE REVIEW

**Comment by gazayas** [comment]
Note to self: I think we'll have to prioritize looking for `scope` blocks when adding the new resource.

**Comment by gazayas** [comment]
We could probably clean up the big conditional in `RoutesFileManipulator#apply` or comment it a little better, but this enables the Action Model scaffolding in the issue mentioned above to work.

Tests on CI appear to be failing due to an Open API issue (I think there were some Open API changes in another repository recently?) but everything is working for me locally, including `test/system/action_models_test.rb` and `test/system/super_scaffolding_test.rb` in the starter repository.

**Comment by gazayas** [comment]
Hey @jagthedrummer, I saw the force push on this and one of the tests that was failing passes now, but it looks like one more still fails due to Open API. I'll leave it as is for now, but just let me know if there's anything you want me to do!

**Review by jagthedrummer — APPROVED** [review]

**Comment by jagthedrummer** [comment]
All good here, @gazayas! We had a little funkiness in CI for a couple of days, but I think things are back to working order now, and this is all passing. Gonna merge it and cut a release.

**Pull request merged**
