### PR TITLE
Ensure we're getting a 200 response when linking to starter repository

### LINKED ISSUE #380: CI script to link to starter repository needs more precise branch check
The tests in #275 should be passing, but we get a strange error from `bin/checkout-and-link-starter-repo` in CI. In #275, the branch is `features/photos-with-active-storage` and doesn't have a matching branch in the starter repository, but CI still tries to clone from it:
Screenshot from 2023-08-05 10-11-55

However, after simply rerunning the test, it uses the `main` branch and passes:
Screenshot from 2023-08-05 10-13-13

[First CI workflow](https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/1056/workflows/ea65fe58-bf65-4d7e-846a-09a3ec213507/jobs/3301) calling a ghost branch
[Second CI workflow](https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/1056/workflows/2cb5d7af-f38d-4566-849d-8cb3050a8564/jobs/3304) using main

## curl output
Here's an example of the curl output which gets the branch from the API:

```
> curl --head -H "Accept: application.vnd.github+json" https://api.github.com/repos/bullet-train-co/bullet_train/branches/features/photos-with-active-storage
HTTP/2 404 
server: GitHub.com
date: Sat, 05 Aug 2023 01:15:12 GMT
content-type: application/json; charset=utf-8
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-ratelimit-limit: 60
x-ratelimit-remaining: 30
x-ratelimit-reset: 1691201105
x-ratelimit-resource: core
x-ratelimit-used: 30
content-length: 122
x-github-request-id: AD2E:1654:2622DE:290DCE:64CDA2AA
```

The value of `x-ratelimit-reset` appears to change, and I could see the regular expression in our script matching `200` even though the response is `404`, so I think we need to change `grep "200"` to something more specific.

### PR DESCRIPTION
**Pull request by gazayas**
Fixes #380.

### CODE REVIEW

**Comment by gazayas** [comment]
Hmm, maybe I'm missing something, I'm getting the same error. Will have to do a little more investigation.

**Comment by jagthedrummer** [comment]
I'd be happy to tackle this on Monday, if you don't want to mess with it over the weekend. I've been down this path a few times recently with the billing gems and was already planning to polish up the branch matching in both the starter repo and `core` so that it's easier to test the joint PRs that are currently open.

**Comment by gazayas** [comment]
@jagthedrummer Thank you, I think I'll take break on this one for a bit!

**Comment by jagthedrummer** [comment]
@gazayas I got this ironed out in https://github.com/bullet-train-co/bullet_train-core/pull/383 and I also added a similar script to the starter repo to pull a matching branch from `core` if it exists. https://github.com/bullet-train-co/bullet_train/pull/825

I'm going to close this and #380. Let me know if anything gives you any trouble on your joint PRs.

**Pull request closed without merging**
